### ISSUE TITLE
Executing inline powershell scripts returns unwanted #< CLIXML outputs streams

### ISSUE THREAD

**Issue by Proxicon** [rundeck-plugins/py-winrm-plugin#39]
**Rundeck Version**: Rundeck 3.2.0-SNAPSHOT
**Platform**: Docker
**OS**: Ubuntu

**PywinRM version**: 2.0.3

**Steps to reproduce**:
**Run job:**

```
- defaultTab: nodes
  description: ''
  executionEnabled: true
  group: Test/Example
  id: 0ff8c815-9a9f-4e1d-a277-1b50b8f9064c
  loglevel: INFO
  name: ls c:\
  nodeFilterEditable: false
  nodefilters:
    dispatch:
      excludePrecedence: true
      keepgoing: true
      rankOrder: ascending
      successOnEmptyNodeFilter: false
      threadcount: '1'
    filter: 'name: OVH.JUMP01.WinRMPython'
  nodesSelectedByDefault: true
  scheduleEnabled: true
  sequence:
    commands:
    - args: -windowstyle hidden
      fileExtension: ps1
      interpreterArgsQuoted: false
      script: $ProgressPreference = 'SilentlyContinue'; ls c:\
      scriptInterpreter: powershell.exe
    keepgoing: false
    strategy: node-first
  uuid: 0ff8c815-9a9f-4e1d-a277-1b50b8f9064c
```

**Returns**

```
    Directory: C:\


Mode                LastWriteTime         Length Name                                                                  
----                -------------         ------ ----                                                                  
d-----        9/28/2019   5:22 PM                inetpub                                                               
d-----        9/15/2018   9:19 AM                PerfLogs                                                              
d-r---       11/21/2019   3:54 PM                Program Files                                                         
d-----       11/19/2019   7:52 PM                Program Files (x86)                                                   
d-----        12/2/2019   3:26 PM                temp                                                                  
d-r---        10/7/2019   4:06 PM                Users                                                                 
d-----       10/12/2019   5:12 PM                Windows     
                                                   
[ERROR  ]  Execution finished with the following error (winrm-exec.py:267)[root]
[ERROR  ]  #< CLIXML
<Objs Version="1.1.0.1" xmlns="http://schemas.microsoft.com/powershell/2004/04"><Obj S="progress" RefId="0"><TN RefId="0"><T>System.Management.Automation.PSCustomObject</T><T>System.Object</T></TN><MS><I64 N="SourceId">1</I64><PR N="Record"><AV>Preparing modules for first use.</AV><AI>0</AI><Nil /><PI>-1</PI><PC>-1</PC><T>Completed</T><SR>-1</SR><SD> </SD></PR></MS></Obj></Objs> (winrm-exec.py:268)[root]

```    
**Screenshot:**

![image](https://user-images.githubusercontent.com/14370617/69963235-7421ec00-1518-11ea-8dfc-fbe602f0bad8.png)

Seeing this on a vanilla ubuntu server + Rundeck Docker image with pywinrm.

Running as a CMD with $ProgressPreference = 'SilentlyContinue appears to silence the output, this however is not applicable for bigger inline scripts.

`$ProgressPreference = 'SilentlyContinue'; ls c:\`
