### ISSUE TITLE
Pywinrm node executor times out at 8 hour mark

### ISSUE THREAD

**Issue by drodriguez-rundeck** [rundeck-plugins/py-winrm-plugin#55]
When using "WinRM Node Executor Python" and executing long running job against a remote node, the job fails exactly at the 8 hour mark. It looks like pywinrm has some sort of timeout (8 hours).
The workaround was to use the default ssh as node executor and the pywinrm as file copier

Steps to reproduce
Create a project, set pywinrm as node executor and default file copier, and create a job that runs a long running batch script in a windows remote node.

Inline script on Rundeck server (RPM Installation- 3.1.2)

![long_running_job](https://user-images.githubusercontent.com/48293178/85882093-a6dd4b80-b7ac-11ea-8647-b3029b685553.jpg)

Batch script to execute on remote Windows node

![script_to_execute](https://user-images.githubusercontent.com/48293178/85882128-ba88b200-b7ac-11ea-9625-38fd20ae0892.jpg)

Sample execution screenshots for reference

![pywinrm1](https://user-images.githubusercontent.com/48293178/85882153-c8d6ce00-b7ac-11ea-8752-7e58c43a6c4f.jpg)

![pywinrm2](https://user-images.githubusercontent.com/48293178/85882174-d12f0900-b7ac-11ea-8fc4-eeb61fa67a34.jpg)

**Comment by oj43085** [comment]
Have you set your timeout properly in winrs at the target server?

winrm get winrm/config 

look at the winrs sub-section

**Comment by drodriguez-rundeck** [comment]
Hi @oj43085 , thanks for the inputs. Yes, I checked winrm config which I am sharing in this post

![winrm_config](https://user-images.githubusercontent.com/48293178/86522897-bd317a00-be32-11ea-9751-8b3ffcf5404c.jpg)

If I set WinRM as default node executor, then the job runs successfully for more than 8 hours (next attached image), but if I set Pywinrm as default executor then the job fails exactly after 8 hours. I am not sure but when using Pywinrm plugin, looks like there is some sort of hardcoded timeout

![winrm_node_executor](https://user-images.githubusercontent.com/48293178/86522974-b8b99100-be33-11ea-8941-5292d18dce16.jpg)

**Comment by nvalenzuela20** [comment]
I can't reproduce the issue in my local environments using Rundeck in a Linux server connecting to windows 10 machine. 
here is the job running more than 8 hours

![image](https://user-images.githubusercontent.com/35808955/90778898-33971800-e2cb-11ea-9e9f-18b943b4f8a8.png)

the project configuration 
```
project.plugin.FileCopier.WinRMcpPython.authtype=basic
project.plugin.FileCopier.WinRMcpPython.interpreter=python3
project.plugin.FileCopier.WinRMcpPython.kinit=kinit
project.plugin.FileCopier.WinRMcpPython.krb5config=/etc/krb5.conf
project.plugin.FileCopier.WinRMcpPython.nossl=false
project.plugin.FileCopier.WinRMcpPython.password_storage_path=keys/windows-server/winpass
project.plugin.FileCopier.WinRMcpPython.username=rundeck-windows
project.plugin.FileCopier.WinRMcpPython.winrmport=5985
project.plugin.FileCopier.WinRMcpPython.winrmtransport=http
project.plugin.NodeExecutor.WinRMPython.authtype=basic
project.plugin.NodeExecutor.WinRMPython.interpreter=python3
project.plugin.NodeExecutor.WinRMPython.kinit=kinit
project.plugin.NodeExecutor.WinRMPython.krb5config=/etc/krb5.conf
project.plugin.NodeExecutor.WinRMPython.nossl=false
project.plugin.NodeExecutor.WinRMPython.password_storage_path=keys/windows-server/winpass
project.plugin.NodeExecutor.WinRMPython.shell=powershell
project.plugin.NodeExecutor.WinRMPython.username=rundeck-windows
project.plugin.NodeExecutor.WinRMPython.winrmport=5985
project.plugin.NodeExecutor.WinRMPython.winrmtransport=http
```
this is the job definition
```
- defaultTab: nodes
  description: ''
  executionEnabled: true
  id: e66377f8-9d5e-4eeb-a595-3c22178102f5
  loglevel: DEBUG
  name: job-node-test
  nodeFilterEditable: false
  nodefilters:
    dispatch:
      excludePrecedence: true
      keepgoing: false
      rankOrder: ascending`
      successOnEmptyNodeFilter: false
      threadcount: '1'
    filter: 'name: Windows'
  nodesSelectedByDefault: true
  plugins:
    ExecutionLifecycle: {}
  scheduleEnabled: true
  schedules: []
  sequence:
    commands:
    - script: |-
        cd /d "c:\Users\rundeck-windows"
        longloop.cmd
    keepgoing: false
    strategy: node-first
  uuid: e66377f8-9d5e-4eeb-a595-3c22178102f5
```
and, this is my PowerShell configuration 

![image (3)](https://user-images.githubusercontent.com/35808955/90779831-2f1f2f00-e2cc-11ea-863a-2d31fb5a6a96.png)
