### ISSUE TITLE
Python module problem

### ISSUE THREAD

**Issue by matthgyver** [rundeck-plugins/py-winrm-plugin#7]
Hi,

At job or command execution, I've this error :

```Traceback (most recent call last):
File "/var/lib/rundeck/libext/cache/py-winrm-plugin-1.0.4/winrm-exec.py", line 1, in <module>
  import winrm
File "build/bdist.linux-x86_64/egg/winrm/__init__.py", line 6, in <module>
File "build/bdist.linux-x86_64/egg/winrm/protocol.py", line 11, in <module>
File "build/bdist.linux-x86_64/egg/winrm/transport.py", line 15, in <module>
File "/usr/lib/python2.7/site-packages/requests-2.18.4-py2.7.egg/requests/__init__.py", line 43, in <module>
  import urllib3
ImportError: No module named urllib3
```

The module is installed yet. I've no problem if I import urllib3 localy from a terminal (I've tested as root and rundeck user)
I can use winrm python library localy. It work well.

I'm on Red Hat Enterprise Linux Server release 7.5 (Maipo).
Pip installed the librarys inside this folder ``/opt/rh/python27/root/usr/lib/python2.7/site-packages``
This folder is on Python system path :
```
Python 2.7.13 (default, Feb  8 2017, 06:57:18) 
[GCC 4.8.5 20150623 (Red Hat 4.8.5-11)] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import sys
>>> print (sys.path)
['', '/opt/rh/python27/root/usr/lib64/python27.zip', '/opt/rh/python27/root/usr/lib64/python2.7', '/opt/rh/python27/root/usr/lib64/python2.7/plat-linux2', '/opt/rh/python27/root/usr/lib64/python2.7/lib-tk', '/opt/rh/python27/root/usr/lib64/python2.7/lib-old', '/opt/rh/python27/root/usr/lib64/python2.7/lib-dynload', '/opt/rh/python27/root/usr/lib64/python2.7/site-packages', '/opt/rh/python27/root/usr/lib/python2.7/site-packages']
```

I don't see where is the problem.
Could you help me please ?

Thank you

**Comment by ltamaster** [comment]
Hi @matthgyver,
I will try to reproduce it.
Can you check the `pip list` command using the rundeck user?
Thanks
Luis

**Comment by matthgyver** [comment]
Hi @ltamaster ,

```
[rundeck@foobar:~]$ pip list
Package       Version  
------------- ---------
asn1crypto    0.24.0   
certifi       2018.4.16
cffi          1.11.5   
chardet       3.0.4    
cryptography  2.2.2    
enum34        1.1.6    
idna          2.6      
ipaddress     1.0.22   
ntlm-auth     1.1.0    
pip           10.0.1   
pycparser     2.18     
pywinrm       0.3.0    
requests      2.18.4   
requests-ntlm 1.1.0    
setuptools    39.2.0   
six           1.11.0   
urllib3       1.22     
xmltodict     0.11.0   
```
Python work directly but I see that I need to type this command to get pip working : ``scl enable python27 bash``

I'm not new on Linux but in RHEL yes and I discover SCL.
I try [this recommandations](https://access.redhat.com/solutions/527703) but without success :-/

Without ``scl enable ...``, pip and import module urllib does'nt work.
It's well an environment problem. I'll continue to search but all suggestions are welcome.

Thank you

**Comment by matthgyver** [comment]
Ok so now I understand better how SCL work, I configured correctly RHEL to load good python version like explain [here](https://access.redhat.com/solutions/527703)

All seems to be ok from a terminal : 
```
[root@foobar:~]# su - rundeck
Dernière connexion : lundi 28 mai 2018 à 10:10:52 CEST sur pts/0
[rundeck@vmi-prod-386:~]$ which python
/opt/rh/python27/root/usr/bin/python
[rundeck@foobar:~]$ python
Python 2.7.13 (default, Feb  8 2017, 06:57:18) 
[GCC 4.8.5 20150623 (Red Hat 4.8.5-11)] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import urllib3
>>> 
```

But the error still here in Rundeck :-/

Have you an idea please ?

PS : this is the full environment of my Rundeck user : 
```
MANPATH=/opt/rh/python27/root/usr/share/man:
XDG_SESSION_ID=1
HOSTNAME=foobar
SHELL=/bin/bash
TERM=xterm-256color
HISTSIZE=1000
X_SCLS=python27 
USER=rundeck
LD_LIBRARY_PATH=/opt/rh/python27/root/usr/lib64
MAIL=/var/spool/mail/rundeck
PATH=/opt/rh/python27/root/usr/bin:/usr/local/bin:/bin:/usr/bin:/usr/local/sbin:/usr/sbin:/opt/puppetlabs/bin:/var/lib/rundeck/.local/bin:/var/lib/rundeck/bin
PWD=/var/lib/rundeck
LANG=fr_FR.UTF-8
HISTCONTROL=ignoredups
SHLVL=1
HOME=/var/lib/rundeck
LOGNAME=rundeck
XDG_DATA_DIRS=/opt/rh/python27/root/usr/share:/usr/local/share:/usr/share
PKG_CONFIG_PATH=/opt/rh/python27/root/usr/lib64/pkgconfig
LESSOPEN=||/usr/bin/lesspipe.sh %s
_=/bin/env
```

**Comment by matthgyver** [comment]
Hi @ltamaster,

I've made some research and tests and I don't understand where is the problem.
Did you know the environment context when a Rundeck job is launched please ?
Have you tryied to reproduce it ?

Thank you

**Comment by ltamaster** [comment]
Hi @matthgyver 

I have been working with a fresh install on docker and vagrant. In both cases, it worked OK for me.
for the first error I saw:
```File "/usr/lib/python2.7/site-packages/requests-2.18.4-py2.7.egg/requests/__init__.py", line 43, in <module>``` 

it seems rundeck user is using the default python installation: /usr/lib/python2.7/site-packages

you can check the user env  o  rundeck, you can use this job:

```
- defaultTab: summary
  description: ''
  executionEnabled: true
  id: 9b2345af-3435-486f-beed-b77422b4fe10
  loglevel: INFO
  name: check-python
  nodeFilterEditable: false
  scheduleEnabled: true
  sequence:
    commands:
    - description: python path
      interpreterArgsQuoted: false
      script: |-
        import sys
        print (sys.path)
      scriptInterpreter: python
    - exec: pip list
    - description: rundeck user env
      exec: env
    keepgoing: false
    strategy: node-first
  uuid: 9b2345af-3435-486f-beed-b77422b4fe10
```

**Comment by matthgyver** [comment]
Hi @ltamaster,

Just running you job and all seem to be OK.
I'm showing the lib in the pip list : 
```

Package       Version
--
14:01:26 |   |   | ------------- ---------
14:01:26 |   |   | asn1crypto    0.24.0
14:01:26 |   |   | certifi       2018.4.16
14:01:26 |   |   | cffi          1.11.5
14:01:26 |   |   | chardet       3.0.4
14:01:26 |   |   | cryptography  2.2.2
14:01:26 |   |   | enum34        1.1.6
14:01:26 |   |   | idna          2.6
14:01:26 |   |   | ipaddress     1.0.22
14:01:26 |   |   | ntlm-auth     1.1.0
14:01:26 |   |   | pip           10.0.1
14:01:26 |   |   | pycparser     2.18
14:01:26 |   |   | pywinrm       0.3.0
14:01:26 |   |   | requests      2.18.4
14:01:26 |   |   | requests-ntlm 1.1.0
14:01:26 |   |   | setuptools    39.2.0
14:01:26 |   |   | six           1.11.0
14:01:26 |   |   | urllib3       1.22
14:01:26 |   |   | xmltodict     0.11.0
```
Could you send me a job definition for a simple command (ex ipconfig) on a windows server node please ? (I'd like to verify something)

Thank you for your help

**Comment by matthgyver** [comment]
Hi @ltamaster,

Could you send me a job definition for a simple command (ex ipconfig) on a windows server node please ? 

Thank you

**Comment by ltamaster** [comment]
here is an example:

```
- defaultTab: summary
  description: ''
  executionEnabled: true
  id: 538264e2-b318-4e9f-bd37-c9605e289f08
  loglevel: INFO
  name: TestCommand
  nodeFilterEditable: false
  nodefilters:
    dispatch:
      excludePrecedence: true
      keepgoing: false
      rankOrder: ascending
      successOnEmptyNodeFilter: false
      threadcount: '1'
    filter: 'osFamily: windows'
  nodesSelectedByDefault: true
  scheduleEnabled: true
  sequence:
    commands:
    - exec: ipconfig
    keepgoing: false
    strategy: node-first
  uuid: 538264e2-b318-4e9f-bd37-c9605e289f08

```


btw, I have a docker image with centos that worked OK with the plugin.
Let me know if that could help you in order to push it on the repo.

Luis

**Comment by matthgyver** [comment]
I've a same error with your job. I don't understand :-/
There is the full output of your check Python job : 
```
['/tmp', '/opt/rh/python27/root/usr/lib64/python27.zip', '/opt/rh/python27/root/usr/lib64/python2.7', '/opt/rh/python27/root/usr/lib64/python2.7/plat-linux2', '/opt/rh/python27/root/usr/lib64/python2.7/lib-tk', '/opt/rh/python27/root/usr/lib64/python2.7/lib-old', '/opt/rh/python27/root/usr/lib64/python2.7/lib-dynload', '/opt/rh/python27/root/usr/lib64/python2.7/site-packages', '/opt/rh/python27/root/usr/lib/python2.7/site-packages']
Package       Version  
------------- ---------
asn1crypto    0.24.0   
certifi       2018.4.16
cffi          1.11.5   
chardet       3.0.4    
cryptography  2.2.2    
enum34        1.1.6    
idna          2.6      
ipaddress     1.0.22   
ntlm-auth     1.1.0    
pip           10.0.1   
pycparser     2.18     
pywinrm       0.3.0    
requests      2.18.4   
requests-ntlm 1.1.0    
setuptools    39.2.0   
six           1.11.0   
urllib3       1.22     
xmltodict     0.11.0   
RD_NODE_OS_FAMILY=unix
MANPATH=/opt/rh/python27/root/usr/share/man:
RD_NODE_DESCRIPTION=Rundeck server node
XDG_SESSION_ID=c6
HOSTNAME=foobar
RD_NODE_USERNAME=rundeck
RD_JOB_WASRETRY=false
SHELL=/bin/bash
HISTSIZE=1000
RD_JOB_THREADCOUNT=1
RD_JOB_RETRYINITIALEXECID=0
RD_JOB_NAME=check-python
RD_JOB_USER_NAME=johndoe
X_SCLS=python27 
USER=rundeck
LD_LIBRARY_PATH=/opt/rh/python27/root/usr/lib64
RD_JOB_USERNAME=johndoe
RD_JOB_PROJECT=MyProject
RD_JOB_EXECID=202
RD_NODE_NAME=localhost
MAIL=/var/spool/mail/rundeck
PATH=/opt/rh/python27/root/usr/bin:/usr/local/bin:/bin:/usr/bin:/usr/local/sbin:/usr/sbin:/opt/puppetlabs/bin:/var/lib/rundeck/.local/bin:/var/lib/rundeck/bin
_=/bin/env
RD_JOB_URL=http://mycomputer:4440/project/MyProject/execution/follow/202
PWD=/var/lib/rundeck
LANG=fr_FR.UTF-8
RD_NODE_OS_NAME=Linux
HISTCONTROL=ignoredups
SHLVL=2
HOME=/var/lib/rundeck
RD_JOB_EXECUTIONTYPE=user
RD_JOB_LOGLEVEL=INFO
RD_JOB_ID=4e0efb88-ec8c-41f2-aa73-df92931yktpi17
RD_NODE_HOSTNAME=localhost
LOGNAME=rundeck
RD_NODE_OS_ARCH=amd64
XDG_DATA_DIRS=/opt/rh/python27/root/usr/share:/usr/local/share:/usr/share
RD_JOB_SERVERURL=http://mycomputer:4440/
RD_NODE_TAGS=local
LESSOPEN=||/usr/bin/lesspipe.sh %s
PKG_CONFIG_PATH=/opt/rh/python27/root/usr/lib64/pkgconfig
XDG_RUNTIME_DIR=/run/user/994
RD_JOB_SUCCESSONEMPTYNODEFILTER=false
RD_JOB_RETRYATTEMPT=0
RD_NODE_OS_VERSION=3.10.0-862.2.3.el7.x86_64
```
All seem to be OK rights ?
Unfortunately I can't use container for my project :-/

Thank you

**Comment by ltamaster** [comment]
@matthgyver what you are using for the python env?
I mean, how did you install /opt/rh/python27/root/usr/lib64/python27.zip ?

**Comment by matthgyver** [comment]
@ltamaster As there was no "pip" installed on my RHEL, I've installed it like described here : https://access.redhat.com/solutions/1519803
It install all that I've in /opt/rh/python27

**Comment by ltamaster** [comment]
@matthgyver 

I tested a way to install the winrm library without pip (and on the local user).
I just download the source of the winrm lib and install it using setup.py

```
- defaultTab: summary
  description: ''
  executionEnabled: true
  id: b094acd6-b15c-451f-9bd9-4be2ca170ae6
  loglevel: INFO
  name: install-winrm
  nodeFilterEditable: false
  scheduleEnabled: true
  sequence:
    commands:
    - script: |-
        wget https://github.com/diyan/pywinrm/archive/master.zip
        unzip master.zip
        cd pywinrm-master

        ls -lrt

        python setup.py install --user
    keepgoing: false
    strategy: node-first
  uuid: b094acd6-b15c-451f-9bd9-4be2ca170ae6
```

Please try running this job on the rundeck server. Maybe you can back to the default python environment on the rundeck user.

Let me know if this help.

BTW, if you have any issue with setuptool library, I have a fix for that.

Luis
